---
- name: Create cluster directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
  - "{{ openshift_download_dir }}"
  - "{{ openshift_client_bin }}"

- name: Download oc tools
  ansible.builtin.get_url:
    url: "{{ openshift_download_base_url }}/ocp/{{ openshift_release }}/{{ item }}"
    dest: "{{ openshift_download_dir }}"
    mode: '0644'
  with_items:
    - openshift-client-linux.tar.gz
    - oc-mirror.tar.gz
    - openshift-install-linux.tar.gz
  register: download_tools

- name: Download trident
  ansible.builtin.get_url:
    url: "https://github.com/NetApp/trident/releases/download/{{ trident_version }}/trident-installer-{{ trident_version  | replace('v', '') }}.tar.gz"
    dest: "{{ openshift_download_dir }}"
    mode: '0644'
  register: download_tridant

- name: Download Butane
  ansible.builtin.get_url:
    url: "{{ openshift_download_base_url }}/butane/latest/butane"
    dest: "{{ openshift_client_bin }}"
    mode: '0644'
  register: download_butane

- name: Extract trident binary
  ansible.builtin.unarchive:
    src: "{{ openshift_download_dir }}/trident-installer-{{ trident_version | replace('v', '') }}.tar.gz"
    remote_src: true
    include:
      - trident-installer/tridentctl
    dest: "{{ openshift_client_bin }}"

- name: Install oc tools
  ansible.builtin.unarchive:
    src: "{{ openshift_download_dir }}/{{ item }}"
    remote_src: true
    exclude:
      - README.md
    dest: "{{ openshift_client_bin }}"
  with_items:
    - openshift-client-linux.tar.gz
    - oc-mirror.tar.gz
    - openshift-install-linux.tar.gz

- name: Move tridentctl to proper location
  ansible.builtin.copy:
    remote_src: true
    src: "{{ openshift_client_bin }}/trident-installer/tridentctl"
    dest: "{{ openshift_client_bin }}/tridentctl"
    mode: '0755'

- name: Remove trident-installer/tridentctl
  ansible.builtin.file:
    path: "{{ openshift_client_bin }}/trident-installer"
    state: absent

### - name: TODO find and list all images to pull for quay 
#  with_itmes:
#    - "{{ quay_images }}"

### Get a way to pull RHCOS iso
# openshift-install coreos print-stream-json
