---
- name: Configure OLM
  ansible.builtin.import_playbook: openshift/cluster/olm.yml
- name: Install NMState Operator
  ansible.builtin.import_playbook: openshift/operator/nmstate.yml
- name: Install node networks
  ansible.builtin.import_playbook: openshift/networks/node.yml
- name: Install pod networks
  ansible.builtin.import_playbook: openshift/networks/pod.yml
- name: Install Trident CLI
  ansible.builtin.import_playbook: openshift/storage/trident/cli.yml
- name: Deploy Trident
  ansible.builtin.import_playbook: openshift/storage/trident/install.yml
- name: Configure Trident Backend
  ansible.builtin.import_playbook: openshift/storage/trident/backend.yml
- name: Configure OCP StorageClass
  ansible.builtin.import_playbook: openshift/storage/trident/storageclass.yml
