# Generate agent
common_openshift_release: 4.16.4
common_previous_openshift_release: 4.16.3
common_trident_version: v24.06.0
<<<<<<< HEAD
mirror_content_oc_mirror_v2: true
=======
>>>>>>> c552822a27926abd81d1bff5a6d6c74635577e74

## Operators To be mirrored, based on index they are in
content_generation_disconnected_operators:
  - redhat-operator-index:
    - name: kubernetes-nmstate-operator
    - name: kubevirt-hyperconverged
    - name: mtv-operator
    - name: openshift-gitops-operator
    - name: container-security-operator
    - name: cluster-logging
    - name: compliance-operator
    - name: local-storage-operator
    - name: lvms-operator
  - redhat-marketplace-index:
  - community-operator-index:
  - certified-operator-index:

## AdditionalImages for oc-mirror to pull. Include version
content_generation_additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/ubi9/ubi:latest
  - name: quay.io/noseka1/toolbox-container:full
  - name: netapp/trident:24.06.0                                        
  - name: docker.io/netapp/trident-autosupport:24.06                    
  - name: registry.k8s.io/sig-storage/csi-provisioner:v4.0.1            
  - name: registry.k8s.io/sig-storage/csi-attacher:v4.6.0               
  - name: registry.k8s.io/sig-storage/csi-resizer:v1.11.0               
  - name: registry.k8s.io/sig-storage/csi-snapshotter:v7.0.2            
  - name: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0 
  - name: netapp/trident-operator:24.06.0 

## URL of file containing pgpkey
mirror_content_pgpkey_location: https://raw.githubusercontent.com/openshift/cluster-update-keys/d44fca585d081a72cb2c67734556a27bbfc9470e/manifests.rhel/0000_90_cluster-update-keys_configmap.yaml
