---
- name: Disable all the default marketplace sources
  shell:
    cmd: |
      oc patch OperatorHub cluster --type json -p '[{"op": "add", "path": "/spec/disableAllDefaultSources", "value": true}]' 

- name: Run workflow for applying ICSP with oc-mirror v1
  include_tasks: mirror-v1.yml
  when: not common_oc_mirror_v2 | bool 

  
- name: Run workflow for applying ICSP with oc-mirror v2
  include_tasks: mirror-v2.yml
  when: common_oc_mirror_v2 | bool