---
- name: NetApp Trident CSI
  hosts: localhost
  gather_facts: false
  # module_defaults:
  #   kubernetes.core.k8s:
  #     kubeconfig: $HOME/.kube/config
  tasks:
    - name: Deploy trident
      register: trident_deploy
      changed_when: "trident_deploy.rc != 0"
      failed_when:
        - false
      ansible.builtin.command: tridentctl install \
        --namespace {{ trident_namespace }} \
        --image-registry {{ trident_registry }} \
        --autosupport-image {{ trident_autosupport }} \
        --trident-image {{ trident_image }}

    - name: Patch Trident controller
      when:
        - trident_controller_annotations is defined
        - trident_controller_annotations.keys() | length > 0
      failed_when:
        - false
      kubernetes.core.k8s:
        state: patched
        kind: Deployment
        name: trident-controller
        namespace: trident-system
        definition:
          spec:
            template:
              metadata:
                annotations:
                  "{{ trident_controller_annotations }}"
