---
- name: Configure OLM
  hosts: localhost
  # module_defaults:
  #   kubernetes.core.k8s:
  #     kubeconfig: $HOME/.kube/config
  gather_facts: false
  tasks:
    - name: Disable default sources
      kubernetes.core.k8s:
        state: patched
        api_version: config.openshift.io/v1
        kind: OperatorHub
        name: cluster
        definition:
          spec:
            disableAllDefaultSources: true

    - name: Enable redhat operator index catalogsource
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: cs-redhat-operator-index
            namespace: openshift-marketplace
          spec:
            image: '{{ registry }}/redhat/redhat-operator-index:v{{ openshift_version }}'
            sourceType: grpc

    - name: Enable certified operator index catalogsource
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: cs-certified-operator-index
            namespace: openshift-marketplace
          spec:
            image: '{{ registry }}/redhat/certified-operator-index:v{{ openshift_version }}'
            sourceType: grpc


    # - name: Enable community operator index catalogsource
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: operators.coreos.com/v1alpha1
    #       kind: CatalogSource
    #       metadata:
    #         name: cs-community-operator-index
    #         namespace: openshift-marketplace
    #       spec:
    #         image: {{ registry }}/redhat/community-operator-index:v{{ openshift_version }}
    #         sourceType: grpc

    # - name: Delete redhat-operator-index pod
    #   kubernetes.core.k8s:

    # - name: Delete certified-operator-index pod
    #   kubernetes.core.k8s:

    # - name: Delete community-operator-index pod
    #   kubernetes.core.k8s:
