---
# defaults file for monitor_deployment

log_level: "info"
bootstrap_complete_text: "bootstrap is complete"
oc_command: "oc get nodes --no-headers | awk '{print $2}' | grep Ready | grep -iv "Not" | wc -l"
node_count: "{{ common_nodes | selectattr('name', 'search', '^master') | list | length }}"
