{{- with .Values.nmstate }}
# Defines the namespace we want to place the nmstate operator into
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kubernetes.io/metadata.name: {{ .target_namespace | default "openshift-nmstate" }}
    name: {{ .target_namespace | default "openshift-nmstate" }}
  name: {{ .target_namespace | default "openshift-nmstate" }}
spec:
  finalizers:
  - kubernetes

{{- end }}