{{- with .Values.mtv }}

---

# Creates a provider resource for migrating VMs into OCP
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: {{ .provider.name | mtv-provider }}
  namespace: {{ .target_namespace | default "openshift-mtv" }}
spec:
  secret: 
    name: {{ .provider.secret }}
    namespace: {{ .target_namespace
  type: openshift
  url: .provider.url
  settings:
    sdkEndpoint: {{ .provider.endpoint }}
    vddkInitImage: {{ .provider.init_image }}
