{{- with .Values.nncps.bond }}
# Defines the standard bond to use in the other nncps configuration
# Referenced in nmstate-nncp-nodes.yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  desiredState:
    interfaces:
      - name: {{ .name }}
        type: bond
        link-aggregation:
          mode: 802.3ad
          port:
{{ toYaml .bond.ports | indent 12 }}
{{- range $i, $curVlan := .vlans }}
      - name: {{ $.Values.nncps.bond.name }}.{{ $curVlan.id }}
        state: up
        type: vlan
        vlan:
          base-iface: {{ $.Values.nncps.bond.name }}
          id: {{ $curVlan.id }}
      - bridge:
          port:
            - name: {{ $.Values.nncps.bond.name }}.{{ $curVlan.id }}
              vlan:
                mode: access
                tag: {{ $curVlan.id }}
        name: br-{{ $.Values.nncps.bond.name }}.{{ $curVlan.id }}
        state: up
        type: linux-bridge 
{{- end -}}
{{- end -}}