{{ range .Values.nncps.nodes }}
---
# Defines node-specific NodeNetworkConfigurationPolicy
# References nncp-bond.yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  nodeSelecotor:
    kubernetes.io/hostname: {{ .node }}
  desiredState:
    interfaces:
  {{ range .vlans }}
    - name: {{ $.Values.nncps.bond.name }}.{{ .id }}
      type: vlan
      state: up
      vlan:
        base-iface: {{ $.Values.nncps.bond.name }}
        id: {{ .id }}
      ipv4:
        enabled: true
        dhcp: false
        address:
        - ip: {{ .ip }}
          prefix-length: 24
  {{- end -}}
{{- end -}}
