apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kuernetes.io/is-default-class: "true"
    argocd.argoproj.io/sync-wave: "5"
  name: basic-csi
parameters:
  backendType: ontap-nas
  fsType: nfs
provisioner: {{ .Values.storage.provisioner }}
volumeBindingMode: WaitForFirstConsumer