# Defaults main.yml for common role
common_openshift_cluster_install_dir: "{{ common_install_dir }}/install-{{ ansible_date_time.date }}"
common_openshift_oc_mirror_dir: "{{ common_openshift_dir }}/images"
common_openshift_client_bin: "{{ common_openshift_dir }}/bin"
common_git_repos_dir: "{{ common_openshift_download_dir }}/git"
common_openshift_download_dir: "{{ common_openshift_dir }}/downloads"
common_openshift_bastion_platform: x86_64
common_openshift_download_base_url: https://mirror.openshift.com/pub/openshift-v4/{{ common_openshift_bastion_platform }}/clients
