#!/usr/bin/ansible-playbook -K
- hosts: localhost
  gather_facts: true
  roles:
    - role: ocp4.disconnected.registry
      tags: registry, stage_0
      when: common_connected_cluster is false
    - role: ocp4.disconnected.mirror_content
      tags: push_cluster_images, stage_0
      vars:
        direction: pull
      when: mirror_content_pull_mirror | bool
    - role: ocp4.disconnected.mirror_content
      tags: push_cluster_images, stage_0
      vars:
        image_source: cluster-images
        direction: push
      when: not common_connected_cluster | bool
    - role: ocp4.disconnected.agent_iso
      tags: agent_install, stage_1
    - role: ocp4.disconnected.media_share
      tags: idrac, stage_1
      vars:
        role: master
    - role: ocp4.disconnected.git
      tags: git, stage_2
    - role: ocp4.disconnected.mirror_content
      tags: mirror_content, stage_2
      vars:
        image_source: operators
        direction: push
      when: not common_connected_cluster | bool
    - role: ocp4.disconnected.monitor_deployment
      tags: agent_install, stage_2
    - role: ocp4.disconnected.apply_icsp
      tags: apply_icsp, stage_2
    - role: ocp4.disconnected.day1_automation
      tags: day1_automation, stage_2

